services:
  web:
    build: .
    image: awsrepo/weather-app:latest
    container_name: weather-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped